name: Docker Image CI

on:
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.8.8 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "virtpubbackend" #Must be unique in Heroku
          heroku_email: "fredrikoden87@gmail.com"

      - run: |
          heroku container:push web -a $APP_NAME
          heroku container:release web -a $APP_NAME



          # -run: |
          #   docker build VirtPub/ -t Test/virtpubregistry:latest
          #   docker push Test/virtpubregistry:latest
