name: Docker

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2


    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal



    - name: 'login via Azure CLI'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        
    - name: 'Build and push frontend image'
      uses: azure/docker-login@v1
      with:
            login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
            username: ${{ secrets.REGISTRY_USERNAME }}
            password: ${{ secrets.REGISTRY_PASSWORD }}
    - run: |
            docker build VirtPub/ -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/virtpubregistry:latest
            docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/virtpubregistry:latest

    - name: 'Build and push backend image'
      uses: azure/docker-login@v1
      with:
            login-server: ${{ secrets.REGISTRY_LOGIN_SERVER_BACKEND }}
            username: ${{ secrets.REGISTRY_USERNAME_BACKEND }}
            password: ${{ secrets.REGISTRY_PASSWORD_BACKEND }}
    - run: |
            docker build VertPub.Backend/ -t ${{ secrets.REGISTRY_LOGIN_SERVER_BACKEND }}/virtpubregistrybackend:latest
            docker push ${{ secrets.REGISTRY_LOGIN_SERVER_BACKEND }}/virtpubregistrybackend:latest
